apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: czworka-quiz-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: czworka-quiz.nmv11
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: czworka-quiz-svc
            port: 
              number: 9890
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: czworka-quiz
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: czworka-quiz
  template:
    metadata:
      labels:
        app: czworka-quiz
    spec:
      containers:
      - name:  czworka-quiz
        env:
        - name: API_KEY
          value: <API_KEY>
        image:  registry.gitlab.com/polskieradio/czworka-quiz:<VERSION>
        ports:
        - containerPort:  3000
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: czworka-quiz-svc
spec:
  selector:
    app: czworka-quiz
  ports:
  - port:  9890
    targetPort:  3000
